name: Docker Image LITASURYA

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          no-cache: true
          tags: |
            ghcr.io/${{ github.repository }}:latest

      - name: Verify PHP Extensions
        run: |
          docker run --rm ghcr.io/${{ github.repository }}:latest php -m

      - name: SSH to server and deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "Logging in to GitHub Container Registry..."
            docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password ${{ secrets.GHCR_PAT }}

            echo "Cleaning up old images..."
            docker image prune -f

            cd litasurya-compose

            echo "Pulling latest image..."
            docker compose pull
            docker compose up -d --force-recreate
            docker compose exec app php artisan migrate --force
